version: "3.0"
services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./prometheusConfig.yml:/prometheusConfig.yml
    command:
      - '--config.file=/prometheusConfig.yml'
    networks:
      - segtaf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    #volumes:
    #  - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - segtaf

networks:
  segtaf:
    driver: bridge
    name: segtaf
